hmrc/agent-epaye-registration

conf/application.conf
=> [JB][APB-1867] Removed DES configurations for DEV and QA

build.sbt, conf/application.conf, project/plugins.sbt
** New feature**
To add config to allow service to be built in new build.
=> to add config to allow OPRA backend new build

app/MicroserviceModule.scala, app/uk/gov/hmrc/agentepayeregistration/config/MicroserviceGlobal.scala, app/uk/gov/hmrc/agentepayeregistration/config/Module.scala, conf/application.conf
**Bug fix**
Changed the way the start up job is set up to try and make sure that it fires up the way it is meant to in production.
=> Amended job setup

app/MicroserviceModule.scala, app/uk/gov/hmrc/agentepayeregistration/config/MicroserviceGlobal.scala, build.sbt, project/plugins.sbt, test/uk/gov/hmrc/agentepayeregistration/audit/AuditServiceSpec.scala
dependAgengtBe - upgrade agent epaye registration backend dependencies
**Maintenance
Upgrading major and minor dependencies to latest versions and fixing tests
=> dependAgentBe initial upgrades

app/MicroserviceModule.scala, app/uk/gov/hmrc/agentepayeregistration/config/MicroserviceGlobal.scala, build.sbt, project/plugins.sbt
**Bug fix**
Update of dependencies and play versions for security upgrade in opra backend
=> play security upgrade for opra backend

build.sbt, project/plugins.sbt
Updated simple reactivemongo
- [ x ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
- [ x ]  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)
- [ x ]  I've executed the acceptance test pack locally to ensure there are no functional regressions
- [ x ]  I've added my code using logical, atomic commits, squashing as appropriate - including the JIRA issue number in the commit message
- [ x ]  I've run a dependency check to ensure all dependencies are up to date
=> Reactivemongo updated to 7.20

app/uk/gov/hmrc/agentepayeregistration/validators/AgentEpayeRegistrationValidator.scala, build.sbt, test/uk/gov/hmrc/agentepayeregistration/validators/AgentEpayeRegistrationValidatorSpec.scala
**Bug fix**
Updated email validation to accept all valid characters.
=> DL-2551 - Updated email validation to use emailaddress library

build.sbt
**Bug fix**
DL-2551 Updated dependencies
=> DL-2551 Updated dependencies

app/config/AppConfig.scala, app/uk/gov/hmrc/agentepayeregistration/audit/AuditService.scala, app/uk/gov/hmrc/agentepayeregistration/connectors/DesConnector.scala, app/uk/gov/hmrc/agentepayeregistration/controllers/AgentEpayeRegistrationController.scala, app/uk/gov/hmrc/agentepayeregistration/controllers/UrlBinders.scala, app/uk/gov/hmrc/agentepayeregistration/models/Address.scala, app/uk/gov/hmrc/agentepayeregistration/models/AgentReference.scala, app/uk/gov/hmrc/agentepayeregistration/models/CreateKnownFactsRequest.scala, app/uk/gov/hmrc/agentepayeregistration/models/Failure.scala, app/uk/gov/hmrc/agentepayeregistration/models/RegistrationDetails.scala, app/uk/gov/hmrc/agentepayeregistration/models/RegistrationExtraction.scala, app/uk/gov/hmrc/agentepayeregistration/models/RegistrationRequest.scala, app/uk/gov/hmrc/agentepayeregistration/repository/AgentEpayeRegistrationRepository.scala, app/uk/gov/hmrc/agentepayeregistration/services/AgentEpayeRegistrationService.scala, app/uk/gov/hmrc/agentepayeregistration/validators/AgentEpayeRegistrationValidator.scala, build.sbt, conf/application.conf, project/build.properties, project/plugins.sbt, test/uk/gov/hmrc/agentepayeregistration/audit/AuditServiceSpec.scala, test/uk/gov/hmrc/agentepayeregistration/controllers/UrlBindersSpec.scala, test/uk/gov/hmrc/agentepayeregistration/model/AddressSpec.scala, test/uk/gov/hmrc/agentepayeregistration/model/AgentReferenceSpec.scala, test/uk/gov/hmrc/agentepayeregistration/validators/AgentEpayeRegistrationValidatorSpec.scala
Updated dependencies for ```agent-epaye-registration```.
=> DL-2687 - OPRA Dependency Updates

app/uk/gov/hmrc/agentepayeregistration/models/AgentReference.scala, build.sbt, it/uk/gov/hmrc/agentepayeregistration/controllers/AgentEpayeRegistrationControllerISpec.scala, it/uk/gov/hmrc/agentepayeregistration/repository/AgentEpayeRegistrationRepositoryISpec.scala, it/uk/gov/hmrc/agentepayeregistration/repository/BaseRepositoryISpec.scala, it/uk/gov/hmrc/agentepayeregistration/support/RegistrationActions.scala, project/plugins.sbt
Removed all compilation and unit test warnings on OPRA.
=> DL-2868 - Remove compilation unit test warnings on OPRA

build.sbt, project/plugins.sbt
**New feature**
DL-3734 - Uplifted simple-reactivemongo & bootstrap-play-26
=> DL-3734 - Uplift simple-reactivemongo & bootstrap-play-26

app/uk/gov/hmrc/agentepayeregistration/connectors/DesConnector.scala, app/uk/gov/hmrc/agentepayeregistration/controllers/AgentEpayeRegistrationController.scala, app/uk/gov/hmrc/agentepayeregistration/services/AgentEpayeRegistrationService.scala, build.sbt, conf/application.conf, conf/logback.xml, it/uk/gov/hmrc/agentepayeregistration/connectors/DesConnectorISpec.scala, project/plugins.sbt, test/uk/gov/hmrc/agentepayeregistration/audit/AuditServiceSpec.scala
=> DL-5486 Dependency updates

build.sbt, project/plugins.sbt, test/uk/gov/hmrc/agentepayeregistration/controllers/UrlBindersSpec.scala
=> Play 2.8 upgrade

build.sbt, conf/application.conf, project/plugins.sbt
Upgraded bootstrap play to 5.24.0 and other general dependency upgrades
=> DL-8085 Dependency upgrades

build.sbt
=> DL-9018 Removing deprecated simple-reactivemongo

app/uk/gov/hmrc/agentepayeregistration/repository/AgentEpayeRegistrationRepository.scala, build.sbt, conf/application.conf, it/uk/gov/hmrc/agentepayeregistration/controllers/AgentEpayeRegistrationControllerISpec.scala, it/uk/gov/hmrc/agentepayeregistration/repository/AgentEpayeRegistrationRepositoryISpec.scala, it/uk/gov/hmrc/agentepayeregistration/repository/BaseRepositoryISpec.scala, it/uk/gov/hmrc/agentepayeregistration/support/MongoApp.scala
=> DL-9018 Migration to hmrc-mongo

app/uk/gov/hmrc/agentepayeregistration/repository/AgentEpayeRegistrationRepository.scala, conf/application.conf
=> DL-9018 Removing mongo TTL config

app/config/AppConfig.scala, app/uk/gov/hmrc/agentepayeregistration/audit/AuditService.scala, app/uk/gov/hmrc/agentepayeregistration/connectors/DesConnector.scala, app/uk/gov/hmrc/agentepayeregistration/controllers/AgentEpayeRegistrationController.scala, app/uk/gov/hmrc/agentepayeregistration/controllers/UrlBinders.scala, app/uk/gov/hmrc/agentepayeregistration/models/Address.scala, app/uk/gov/hmrc/agentepayeregistration/models/AgentReference.scala, app/uk/gov/hmrc/agentepayeregistration/models/CreateKnownFactsRequest.scala, app/uk/gov/hmrc/agentepayeregistration/models/Failure.scala, app/uk/gov/hmrc/agentepayeregistration/models/RegistrationDetails.scala, app/uk/gov/hmrc/agentepayeregistration/models/RegistrationExtraction.scala, app/uk/gov/hmrc/agentepayeregistration/models/RegistrationRequest.scala, app/uk/gov/hmrc/agentepayeregistration/repository/AgentEpayeRegistrationRepository.scala, app/uk/gov/hmrc/agentepayeregistration/services/AgentEpayeRegistrationService.scala, app/uk/gov/hmrc/agentepayeregistration/validators/AgentEpayeRegistrationValidator.scala, build.sbt, conf/application-json-logger.xml, conf/application.conf, it/uk/gov/hmrc/agentepayeregistration/controllers/AgentEpayeRegistrationControllerISpec.scala, it/uk/gov/hmrc/agentepayeregistration/repository/AgentEpayeRegistrationRepositoryISpec.scala, it/uk/gov/hmrc/agentepayeregistration/support/MongoApp.scala, project/build.properties, project/plugins.sbt, test/uk/gov/hmrc/agentepayeregistration/audit/AuditServiceSpec.scala, test/uk/gov/hmrc/agentepayeregistration/controllers/UrlBindersSpec.scala, test/uk/gov/hmrc/agentepayeregistration/model/AddressSpec.scala, test/uk/gov/hmrc/agentepayeregistration/model/AgentReferenceSpec.scala, test/uk/gov/hmrc/agentepayeregistration/validators/AgentEpayeRegistrationValidatorSpec.scala
=> DL-9987 - Copyright updates

README.md
=> DL-9877 update READ.me file

app/config/AppConfig.scala
=> Setting up OPRA api to work in QA

app/uk/gov/hmrc/agentepayeregistration/utils/EmailAddress.scala, app/uk/gov/hmrc/agentepayeregistration/utils/StringValue.scala, app/uk/gov/hmrc/agentepayeregistration/validators/AgentEpayeRegistrationValidator.scala, project/AppDependencies.scala, project/plugins.sbt
DL-15069: Upgrading dependencies version to the latest.
Upgrade done in org.playframework, sbt.build, mongo,bootstrap versions
=> DL-15069: Upgrading dependencies version to the latest.

project/AppDependencies.scala
DL-15278:Rectifying bobby violation
=> DL-15278:Rectifying bobby violation

build.sbt, project/AppDependencies.scala, project/build.properties, project/plugins.sbt
=> DL-15856: Dependency upgrades

project/AppDependencies.scala, project/plugins.sbt
=> DL-17178: Updated bootstrap version
